// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbRM8X2OAlx86m0lHPf1B4gnT7DyHA5iU',
    appId: '1:636186498723:web:tamkeened',
    messagingSenderId: '636186498723',
    projectId: 'tamkeened-8821e',
    authDomain: 'tamkeened-8821e.firebaseapp.com',
    storageBucket: 'tamkeened-8821e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRM8X2OAlx86m0lHPf1B4gnT7DyHA5iU',
    appId: '1:636186498723:android:60eb03dd71111867149116',
    messagingSenderId: '636186498723',
    projectId: 'tamkeened-8821e',
    storageBucket: 'tamkeened-8821e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbRM8X2OAlx86m0lHPf1B4gnT7DyHA5iU',
    appId: '1:636186498723:ios:tamkeened',
    messagingSenderId: '636186498723',
    projectId: 'tamkeened-8821e',
    storageBucket: 'tamkeened-8821e.firebasestorage.app',
    iosClientId: '636186498723-tamkeened.apps.googleusercontent.com',
    iosBundleId: 'com.tamkeen.tamkeened',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbRM8X2OAlx86m0lHPf1B4gnT7DyHA5iU',
    appId: '1:636186498723:macos:tamkeened',
    messagingSenderId: '636186498723',
    projectId: 'tamkeened-8821e',
    storageBucket: 'tamkeened-8821e.firebasestorage.app',
    iosClientId: '636186498723-tamkeened.apps.googleusercontent.com',
    iosBundleId: 'com.tamkeen.tamkeened',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbRM8X2OAlx86m0lHPf1B4gnT7DyHA5iU',
    appId: '1:636186498723:windows:tamkeened',
    messagingSenderId: '636186498723',
    projectId: 'tamkeened-8821e',
    authDomain: 'tamkeened-8821e.firebaseapp.com',
    storageBucket: 'tamkeened-8821e.firebasestorage.app',
  );
}